esphome:
  name: transit-tracker-hebrew
  friendly_name: Transit Tracker (Hebrew)

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
  - source:
      type: local
      path: ../components

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    text_sensor: ERROR

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "ReplaceMe"
  password: "ReplaceMe!"
  power_save_mode: "NONE"

  ap:
    ssid: "TransitTracker Fallback Hotspot"
    password: "59541bEJiaf3"

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 255
    lambda: |-
      id(tracker).draw_schedule();

font:
  - file: "fonts/ChavaRegular.ttf"
    id: chava
    size: 12
    bpp: 2
    glyphs:
      - "אבגדהוזחטיכךלמםנןסעפףצץקרשת"
      - "0123456789.:;!?... "
      - "־"

time:
  - platform: sntp
    id: sntp_time
    timezone: Asia/Jerusalem

color:
  - id: default_route
    hex: "028e51"

transit_tracker:
  id: tracker
  base_url: "wss://tt.horner.tj/"
  limit: 3
  feed_code: "il-mot"
  rtl_mode: true
  scroll_headsigns: true
  show_units: short
  stops:
    - stop_id: "YOUR_STOP_ID_HERE"
      time_offset: -5min
      routes:
        - "YOUR_ROUTE_ID_HERE"
  default_route_color: default_route

